# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-24 11:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality_area',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hilucs_land_use_value', models.IntegerField(default=0)),
                ('original_land_use_value', models.TextField()),
                ('geometry_source', django.contrib.postgres.fields.jsonb.JSONField()),
                ('attribute_source', django.contrib.postgres.fields.jsonb.JSONField()),
                ('municipal_code', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
