# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-24 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_land_use', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality_area',
            name='attribute_source',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='municipality_area',
            name='geometry_source',
            field=models.TextField(),
        ),
    ]
