# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-24 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_land_use', '0002_auto_20170124_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipality_area',
            old_name='end_date',
            new_name='validfrom',
        ),
        migrations.RenameField(
            model_name='municipality_area',
            old_name='start_date',
            new_name='validto',
        ),
    ]
